config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'
  get 'sessions/destroy'
  get 'users/create'

  resources :books
  resources :authors

  namespace :api do
    resources :books do
      collection do
        get 'filter_title'
        get 'filter_author'
        get 'filter_price'
      end
    end
    resources :favorites, only: [:create, :destroy, :index, :favorite_per_user]
    resources :authors, only: [:index, :show, :create, :update, :destroy]
    resources :publishers, only: [:index, :show, :create, :update, :destroy]
    post 'favorites/:user_id/:book_id', to: 'favorites#create', as: :add_favorite
    delete 'favorites/:user_id/:book_id', to: 'favorites#destroy', as: :remove_favorite
    get 'favorites/:user_id', to: 'favorites#favorite_per_user', as: :favorite_per_user
  end
  resources :users, only: [:create]
  post 'register', to: 'users#create'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :author
  has_many :favorites
  has_many :favorited_by, through: :favorites, source: :user

  def as_json(options = {})
    super(options.merge({
                          methods: [:image_url],
                        }))
  end

  def image_url
    if image.attached?
      # Use the Cloudinary service URL
      Cloudinary::Utils.cloudinary_url(image.key, secure: true)
    else
      nil
    end
  end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @books = Book.order(created_at: :desc)
    render json: @books.to_json(include: [:image])
  end

  def show
    @book = Book.find_by_id(params[:id])
    render json: {
      id: @book.id,
      title: @book.title,
      price: @book.price,
      author: @book.author,
      description: @book.description,
      isbn: @book.isbn,
      genre: @book.genre,
      image: url_for(@book.image),
      date: @book.date_of_publication
      # Add other attributes as needed
    }
  end

  def create
    @book = Book.create(book_params)

    if @book.valid?
      render json: @book.to_json(include: [:image]), status: :created
    else
      render json: { error: 'Failed to create the book', details: @book.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      render json: @book.to_json(include: [:image]), status: :ok
    else
      render json: { error: 'Failed to update the book', details: @book.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find_by_id(params[:id])
    @book.destroy
    render json: { message: 'Book Deleted' }
  end

  private

  def book_params
    params.require(:book).permit(:title, :price, :genre, :author, :description, :image, :isbn, :date_of_publication)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
    @authors = Author.all
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @authors = Author.all
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.fetch(:book, {})
  end

  def book_params
    params.require(:book).permit(:title, :price, :genre, :author, :description, :image, :isbn, :date_of_publication, :author_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
<div>
    <strong>Title:</strong>
    <%= book.title %>
        </div>
<div>
    <strong>Price:</strong>
    <%= book.price %>
        </div>
<div>
    <strong>Author:</strong>
    <%= book.author.name %>
        </div>
</div>
<div>
<%= book.genre%>

</div>

<% if book.image.attached? %>
    <%= cl_image_tag book.image.key, :width=>150, :crop=>"fill" %>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with(model: @book) do |form| %>
  <% if @book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div> 
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
<div>
  <%= form.label :author_id %>
  <%= form.collection_select(:author_id, @authors, :id, :name, prompt: "Select an author") %>
</div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<div>
    <%= form.label :date_of_publication%>
    <%= form.date_field :date_of_publication %>
  </div>
  <div>
    <%= form.label :isbn %>
    <%= form.number_field :isbn %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :genre %>
    <%= form.text_field :genre %>

  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>


<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>